soal_kuis = {
    "1": [
        ("1. Apa yang dimaksud dengan media transmisi dalam jaringan?", "saluran untuk mengirim data antar perangkat"),
        ("2. Apa perbedaan antara guided media dan unguided media?", "guided media menggunakan kabel fisik, unguided media menggunakan gelombang udara"),
        ("3. Sebutkan 3 jenis guided media!", "utp, coaxial, fiber optik"),
        ("4. Sebutkan 2 jenis unguided media!", "wifi dan bluetooth"),
        ("5. Apa kelebihan UTP dibandingkan coaxial?", "lebih murah dan fleksibel"),
        ("6. Apa kelemahan UTP dalam transmisi data?", "mudah terganggu oleh interferensi elektromagnetik"),
        ("7. Apa keunggulan kabel coaxial dibanding UTP?", "lebih tahan terhadap interferensi"),
        ("8. Media apa yang umum digunakan pada CCTV?", "kabel coaxial"),
        ("9. Kenapa fiber optik cocok untuk backbone jaringan?", "cepat, bebas interferensi, dan jangkauan jauh"),
        ("10. Sebutkan tiga lapisan utama dalam fiber optik!", "core, cladding, buffer coating"),
        ("11. Apa kelemahan utama fiber optik?", "biaya instalasi mahal"),
        ("12. Apa nama media transmisi yang mengirim sinyal melalui cahaya?", "fiber optik"),
        ("13. Kabel manakah yang menggunakan konduktor pusat dan pelindung logam?", "coaxial"),
        ("14. Apa fungsi cladding dalam fiber optik?", "memantulkan cahaya agar tetap dalam core"),
        ("15. Jenis kabel twisted pair tanpa pelindung disebut?", "UTP"),
        ("16. Apa arti dari singkatan UTP?", "unshielded twisted pair"),
        ("17. Apa kekurangan utama dari media nirkabel?", "mudah terganggu sinyal dan tidak aman"),
        ("18. Perangkat apa yang menggunakan bluetooth?", "headset, mouse, speaker"),
        ("19. Apa fungsi dari guided media?", "menyalurkan data melalui jalur fisik"),
        ("20. Sinyal pada media nirkabel dikirim melalui apa?", "gelombang elektromagnetik"),
        ("21. Media apa yang cocok digunakan untuk perangkat bergerak?", "unguided media"),
        ("22. Jelaskan kelebihan utama dari guided media!", "stabil dan tidak mudah terganggu"),
        ("23. Sebutkan contoh media transmisi gelombang elektromagnetik!", "wifi"),
        ("24. Apa fungsi twisted pada kabel UTP?", "mengurangi interferensi"),
        ("25. Kapan kita lebih baik menggunakan fiber optik daripada UTP?", "untuk transmisi jarak jauh dan kecepatan tinggi"),
        ("26. Kabel apa yang banyak digunakan dalam jaringan LAN?", "UTP"),
        ("27. Apa dampak dari interferensi elektromagnetik pada kabel?", "mengganggu kualitas sinyal"),
        ("28. Bagaimana gelombang radio digunakan dalam jaringan?", "mengirim sinyal melalui udara"),
        ("29. Apa nama standar nirkabel yang umum di laptop dan smartphone?", "wifi"),
        ("30. Apa risiko utama dari penggunaan media nirkabel?", "keamanan dan interferensi"),
        ("31. Apa peran buffer coating pada fiber optik?", "melindungi bagian dalam dari kerusakan fisik"),
        ("32. Media transmisi apa yang paling tahan terhadap gangguan listrik?", "fiber optik"),
        ("33. Kabel apa yang memiliki biaya pemasangan paling murah?", "UTP"),
        ("34. Apa ciri khas kabel STP dibanding UTP?", "memiliki pelindung tambahan"),
        ("35. Apa kelemahan utama dari kabel coaxial?", "lebih mahal dan sulit dipasang"),
        ("36. Bagaimana data dikirim dalam kabel fiber optik?", "dalam bentuk cahaya"),
        ("37. Apa media transmisi paling cepat saat ini?", "fiber optik"),
        ("38. Apa kelebihan utama WiFi dibandingkan kabel?", "tidak butuh kabel, fleksibel"),
        ("39. Kenapa jaringan kabel lebih stabil dari nirkabel?", "tidak terganggu oleh sinyal luar"),
        ("40. Apa itu interferensi elektromagnetik?", "gangguan dari medan listrik atau magnet"),
        ("41. Apa jenis frekuensi yang digunakan oleh WiFi?", "2.4 GHz dan 5 GHz"),
        ("42. Mengapa kabel STP lebih tahan interferensi dibanding UTP?", "karena memiliki lapisan pelindung tambahan"),
        ("43. Apa singkatan dari STP dalam media transmisi?", "shielded twisted pair"),
        ("44. Mengapa kabel coaxial cocok untuk CCTV?", "karena tahan interferensi dan sinyal stabil"),
        ("45. Apa penyebab utama penurunan kualitas sinyal pada kabel UTP?", "interferensi elektromagnetik"),
        ("46. Apa keuntungan menggunakan gelombang radio sebagai media transmisi?", "dapat menjangkau area luas tanpa kabel"),
        ("47. Sebutkan dua kelemahan dari media nirkabel!", "mudah terganggu dan tidak aman"),
        ("48. Media apa yang digunakan pada jaringan internet rumahan tanpa kabel?", "wifi"),
        ("49. Apa jenis kabel yang digunakan untuk transmisi sinyal video di TV kabel?", "coaxial"),
        ("50. Apa nama bagian fiber optik yang menghantarkan cahaya?", "core"),
        ("51. Apa yang dilakukan cladding terhadap cahaya dalam fiber optik?", "memantulkan cahaya kembali ke core"),
        ("52. Apa fungsi utama media transmisi dalam jaringan?", "mengantarkan data dari satu perangkat ke perangkat lain"),
        ("53. Apa jenis media transmisi paling aman terhadap penyadapan?", "fiber optik"),
        ("54. Apa penyebab utama gangguan sinyal pada media wireless?", "interferensi dari frekuensi lain"),
        ("55. Mengapa Bluetooth hanya digunakan untuk jarak dekat?", "karena daya pancarnya kecil"),
        ("56. Apa jenis gelombang yang digunakan dalam Wi-Fi?", "gelombang elektromagnetik"),
        ("57. Apa yang dimaksud dengan media transmisi guided?", "media yang menggunakan kabel fisik"),
        ("58. Apa kelebihan menggunakan infrared?", "memiliki privasi tinggi karena bersifat line-of-sight"),
        ("59. Bagaimana bentuk fisik kabel UTP?", "pasangan kabel tembaga yang dipilin"),
        ("60. Dalam kondisi apa WiFi lebih dipilih daripada kabel LAN?", "saat mobilitas perangkat tinggi"),
        ("61. Kabel mana yang paling sensitif terhadap gangguan listrik?", "UTP"),
        ("62. Apa nama lapisan luar pada kabel coaxial?", "jacket luar"),
        ("63. Apa media transmisi terbaik untuk transfer data berkecepatan tinggi jarak jauh?", "fiber optik"),
        ("64. Bagaimana cara kerja transmisi cahaya dalam fiber optik?", "cahaya dipantulkan dalam core oleh cladding"),
        ("65. Apa yang dimaksud dengan media transmisi unguided?", "media tanpa kabel, menggunakan udara"),
        ("66. Media transmisi apa yang menggunakan serat kaca?", "fiber optik"),
        ("67. Apa kelebihan utama dari coaxial dibanding UTP?", "tahan terhadap interferensi"),
        ("68. Bagaimana cara kerja Bluetooth?", "mengirim data melalui gelombang radio jarak dekat"),
        ("69. Media mana yang paling ekonomis untuk instalasi jaringan skala kecil?", "UTP"),
        ("70. Apa yang membedakan media guided dan unguided dalam aspek fisik?", "guided memiliki kabel fisik, unguided tidak"),
        ("71. Apa contoh penggunaan nyata dari fiber optik?", "backbone internet dan antar gedung"),
        ("72. Apa dampak dari pemasangan kabel UTP yang terlalu panjang?", "sinyal melemah"),
        ("73. Apa manfaat pemilinan kabel pada UTP?", "mengurangi interferensi antara kabel"),
        ("74. Dalam jaringan LAN, media apa yang paling sering digunakan?", "UTP"),
        ("75. Media transmisi apa yang memungkinkan sinyal dikirim tanpa koneksi fisik?", "unguided media"),
        ("76. Apa contoh perangkat yang biasa menggunakan infrared?", "remote tv"),
        ("77. Apa nama bagian pelindung logam pada kabel coaxial?", "shielding"),
        ("78. Apa alasan kabel coaxial lebih tahan gangguan dibanding UTP?", "karena memiliki shielding"),
        ("79. Apa itu bandwidth dalam konteks media transmisi?", "kapasitas maksimum pengiriman data"),
        ("80. Apa jenis kabel yang dapat mengirim sinyal cahaya?", "fiber optik"),
        ("81. Mengapa STP digunakan di area banyak gangguan elektromagnetik?", "karena lebih terlindungi"),
        ("82. Apa yang membuat fiber optik tidak terpengaruh oleh medan listrik?", "karena menggunakan cahaya, bukan listrik"),
        ("83. Apa risiko terbesar dari media nirkabel?", "interferensi dan keamanan"),
        ("84. Sebutkan contoh jaringan yang cocok menggunakan Wi-Fi!", "jaringan rumah tangga"),
        ("85. Apa kelebihan utama dari media wireless?", "mudah dipasang dan mendukung mobilitas"),
        ("86. Apa lapisan pelindung luar pada fiber optik disebut?", "buffer coating"),
        ("87. Apa itu interferensi dalam media transmisi?", "gangguan dari sinyal eksternal"),
        ("88. Kabel mana yang paling ringan dan fleksibel untuk instalasi?", "UTP"),
        ("89. Jenis media apa yang cocok untuk daerah sulit dijangkau kabel?", "unguided media"),
        ("91. Apa itu sinyal dalam konteks media transmisi?", "gelombang pembawa informasi"),
        ("92. Apa jenis media transmisi yang membutuhkan SFP atau konektor khusus?", "fiber optik"),
        ("93. Mengapa data di fiber optik sulit disadap?", "karena tidak memancarkan sinyal elektromagnetik"),
        ("94. Dalam skenario outdoor, media mana yang lebih praktis?", "nirkabel"),
        ("95. Apa keuntungan utama menggunakan twisted pair dibanding coaxial?", "lebih murah dan lebih ringan"),
        ("96. Apa frekuensi umum yang digunakan oleh Bluetooth?", "2.4 GHz"),
        ("97. Sebutkan tiga perangkat yang biasa menggunakan WiFi!", "laptop, smartphone, printer"),
        ("98. Apa yang dimaksud dengan gelombang elektromagnetik?", "gelombang energi yang merambat melalui udara"),
        ("99. Apa kekurangan dari gelombang radio?", "mudah terganggu oleh sinyal lain"),
        ("100. Apa keuntungan kabel fiber optik dalam hal kecepatan?", "memiliki bandwidth tinggi"),
    ],
    
    "2": [
        ("1. Apa yang dimaksud dengan fiber optik?", "Media transmisi yang mengirimkan data melalui pulsa cahaya dalam serat kaca atau plastik"),
        ("2. Apa fungsi utama dari core dalam fiber optik?", "Menjadi jalur utama rambatan cahaya"),
        ("3. Apa bahan utama dari core?", "Silika murni atau plastik dengan indeks bias tinggi"),
        ("4. Apa itu cladding dalam fiber optik?", "Lapisan yang mengelilingi core dan memantulkan cahaya dengan pantulan total internal"),
        ("5. Mengapa cladding memiliki indeks bias lebih rendah?", "Agar cahaya tetap terpantul di dalam core melalui pantulan total internal"),
        ("6. Apa fungsi utama dari coating atau buffer?", "Melindungi fiber dari goresan, tekanan, dan kelembaban"),
        ("7. Apa itu pantulan total internal?", "Cahaya yang masuk pada sudut tertentu terpantul sempurna di dalam core karena perbedaan indeks bias"),
        ("8. Sebutkan syarat terjadinya pantulan total internal!", "Sudut datang lebih besar dari sudut kritis dan ada perbedaan indeks bias"),
        ("9. Mengapa fiber optik mampu menjangkau jarak jauh tanpa repeater?", "Karena pantulan total internal membuat cahaya tetap berada di dalam core tanpa banyak kehilangan"),
        ("10. Apa jenis sumber cahaya yang digunakan dalam fiber optik?", "Laser diode dan LED"),
        ("11. Apa keunggulan laser diode?", "Transmisi cepat dan jarak jauh, cocok untuk single mode"),
        ("12. Apa kelemahan laser diode?", "Mahal dan sensitif"),
        ("13. Apa kelebihan LED sebagai sumber cahaya?", "Murah, awet, cocok untuk jarak pendek"),
        ("14. Apa kelemahan LED?", "Kecepatannya rendah dan tidak cocok untuk jarak jauh"),
        ("15. Apa itu single mode fiber?", "Jenis fiber optik dengan core sangat kecil yang hanya membawa satu jalur cahaya"),
        ("16. Apa itu multimode fiber?", "Jenis fiber optik dengan core lebih besar yang membawa banyak jalur cahaya"),
        ("17. Apa perbedaan utama antara single mode dan multimode?", "Single mode untuk jarak jauh dan cepat, multimode untuk jarak pendek"),
        ("18. Apa itu bending loss?", "Kehilangan sinyal karena fiber ditekuk terlalu tajam"),
        ("19. Apa itu macro-bending?", "Kehilangan karena tikungan besar saat pemasangan"),
        ("20. Apa itu micro-bending?", "Kehilangan karena tekanan mikroskopis dalam struktur kabel"),
        ("21. Bagaimana cara menghindari bending loss?", "Hindari radius tikungan kecil dan gunakan pelindung lentur"),
        ("22. Sebutkan keunggulan fiber optik!", "Bandwidth tinggi, tahan interferensi, ringan, aman, dan jangkauan jauh"),
        ("23. Mengapa fiber optik tahan terhadap interferensi elektromagnetik?", "Karena cahaya tidak dipengaruhi gelombang elektromagnetik"),
        ("24. Apakah fiber optik mudah disadap?", "Tidak, karena tidak memancarkan gelombang elektromagnetik ke luar"),
        ("25. Apa ukuran diameter core pada single mode fiber?", "Sekitar 8–10 mikrometer"),
        ("26. Apa ukuran diameter core pada multimode fiber?", "Sekitar 50–62,5 mikrometer"),
        ("27. Apa yang terjadi jika sudut datang cahaya lebih kecil dari sudut kritis?", "Cahaya akan keluar dari core dan terjadi kehilangan sinyal"),
        ("28. Apa yang dimaksud dengan indeks bias?", "Kemampuan bahan memperlambat kecepatan cahaya"),
        ("29. Mengapa perlu coating dalam fiber optik?", "Untuk melindungi serat dari kerusakan fisik dan kelembaban"),
        ("30. Sebutkan tiga lapisan utama dalam struktur fiber optik!", "Core, cladding, coating"),
        ("31. Apa perbedaan antara cladding dan coating?", "Cladding memantulkan cahaya, coating melindungi dari kerusakan fisik"),
        ("32. Mengapa cahaya bisa tetap berada dalam fiber?", "Karena pantulan total internal di antara core dan cladding"),
        ("33. Mengapa laser lebih cocok untuk single mode?", "Karena menghasilkan cahaya koheren dengan penyebaran minimal"),
        ("34. Bagaimana LED menghasilkan cahaya?", "Dengan mengubah energi listrik menjadi cahaya melalui semikonduktor"),
        ("35. Mengapa LED cocok untuk multimode?", "Karena memiliki penyebaran cahaya yang luas dan cukup untuk jarak pendek"),
        ("36. Apa itu attenuation dalam fiber optik?", "Pelemahan sinyal cahaya sepanjang serat optik"),
        ("37. Apa yang menyebabkan attenuation?", "Penyebaran cahaya, penyerapan, dan scattering"),
        ("38. Apa itu dispersion?", "Penyebaran pulsa cahaya yang menyebabkan sinyal melebar"),
        ("39. Bagaimana dispersion memengaruhi transmisi?", "Menurunkan kualitas sinyal pada jarak jauh"),
        ("40. Apa solusi untuk dispersion?", "Gunakan single mode fiber dan teknik kompensasi dispersion"),
        ("41. Apa keunggulan utama fiber optik dibanding kabel tembaga?", "Kecepatan tinggi, jangkauan jauh, dan tahan interferensi"),
        ("42. Mengapa fiber optik lebih ringan dari kabel tembaga?", "Karena terbuat dari kaca atau plastik yang tipis"),
        ("43. Apa manfaat keamanan fiber optik?", "Sulit disadap dan tidak memancarkan sinyal ke luar"),
        ("44. Apa jenis konektor umum dalam fiber optik?", "SC, ST, LC"),
        ("45. Apa fungsi konektor pada fiber optik?", "Menyambungkan serat optik dengan perangkat lain"),
        ("46. Mengapa instalasi fiber optik butuh presisi tinggi?", "Karena ukuran core sangat kecil dan sensitif"),
        ("47. Apa itu splicing dalam fiber optik?", "Penyambungan dua serat optik"),
        ("48. Apa dua jenis splicing?", "Fusion splicing dan mechanical splicing"),
        ("49. Apa kelebihan fusion splicing?", "Lebih kuat dan sedikit kehilangan sinyal"),
        ("50. Apa alat ukur yang digunakan untuk fiber optik?", "OTDR (Optical Time Domain Reflectometer)"),
        ("51. Apa fungsi OTDR?", "Mengukur jarak, lokasi kerusakan, dan attenuation"),
        ("52. Apa itu repeater dalam jaringan fiber optik?", "Alat untuk memperkuat sinyal dalam jarak jauh"),
        ("53. Kapan repeater dibutuhkan?", "Jika jarak transmisi melebihi batas tanpa penguat"),
        ("54. Apa peran jacket dalam kabel fiber optik?", "Melindungi keseluruhan serat dari kerusakan lingkungan"),
        ("55. Apa warna standar untuk single mode fiber?", "Kuning"),
        ("56. Apa warna standar untuk multimode fiber?", "Oranye atau aqua"),
        ("57. Apa keuntungan menggunakan fiber optik dalam jaringan backbone?", "Mengurangi latency dan meningkatkan kapasitas data"),
        ("58. Apa itu numerical aperture (NA)?", "Kemampuan core untuk menerima cahaya masuk"),
        ("59. Bagaimana NA mempengaruhi fiber optik?", "Semakin tinggi NA, semakin banyak cahaya yang bisa diterima"),
        ("60. Apa jenis-jenis transmisi fiber optik?", "Transmisi analog dan digital"),
        ("61. Apa itu mode dalam fiber optik?", "Jalur perambatan cahaya dalam core"),
        ("62. Apa itu modal dispersion?", "Perbedaan waktu tempuh antar mode dalam multimode fiber"),
        ("63. Mengapa modal dispersion tidak terjadi di single mode?", "Karena hanya satu jalur cahaya yang dirambatkan"),
        ("64. Apa fungsi pelindung lentur (bending protector)?", "Mencegah bending loss akibat tikungan tajam"),
        ("65. Mengapa instalasi fiber optik perlu pelindung tambahan?", "Agar tahan terhadap tekanan dan perubahan lingkungan"),
        ("66. Apa keunggulan fiber optik dalam sistem komunikasi bawah laut?", "Tahan gangguan dan dapat mentransmisikan data jarak jauh"),
        ("67. Bagaimana cara menghindari kehilangan daya pada sambungan?", "Gunakan teknik splicing yang tepat dan konektor berkualitas"),
        ("68. Apakah fiber optik bisa digunakan di rumah?", "Ya, terutama untuk koneksi internet berkecepatan tinggi (FTTH)"),
        ("69. Apa itu FTTH?", "Fiber To The Home – jaringan fiber langsung ke rumah pengguna"),
        ("70. Mengapa fiber optik cocok untuk data center?", "Mampu menangani volume data besar dengan kecepatan tinggi"),
        ("71. Apakah fiber optik menghantarkan listrik?", "Tidak, hanya menghantarkan cahaya"),
        ("72. Apakah fiber optik bisa terbakar?", "Tidak mudah terbakar karena berbahan kaca atau plastik"),
        ("73. Apa bahaya utama dalam pemasangan fiber optik?", "Pecahan kecil serat yang bisa melukai atau masuk ke tubuh"),
        ("74. Bagaimana menghindari bahaya saat instalasi?", "Gunakan alat pelindung dan tempatkan sisa fiber dalam wadah tertutup"),
        ("75. Apa keuntungan jangka panjang fiber optik?", "Biaya perawatan rendah dan masa pakai lama"),
        ("76. Bagaimana fiber optik membantu pengurangan polusi elektromagnetik?", "Tidak menghasilkan gelombang elektromagnetik"),
        ("77. Apa dampak jika fiber terkena kelembaban tinggi?", "Bisa menyebabkan korosi atau pelemahan lapisan pelindung"),
        ("78. Apa itu bandwidth dalam konteks fiber optik?", "Jumlah data yang dapat ditransmisikan dalam waktu tertentu"),
        ("79. Bagaimana fiber optik mendukung jaringan 5G?", "Menjadi tulang punggung transmisi data berkecepatan tinggi"),
        ("80. Apa tantangan utama instalasi fiber optik?", "Kebutuhan teknis tinggi dan biaya awal yang mahal"),
        ("81. Mengapa kabel fiber tidak boleh ditekuk tajam saat dipasang?", "Karena menyebabkan kehilangan cahaya (bending loss)"),
        ("82. Apa fungsi lapisan buffer dalam struktur kabel?", "Memberi fleksibilitas dan perlindungan tambahan"),
        ("83. Mengapa fiber optik ideal untuk sistem keamanan?", "Sulit disadap dan transmisi sangat stabil"),
        ("84. Apa yang dimaksud dengan dispersion compensation?", "Teknik untuk memperbaiki penyebaran sinyal dalam fiber"),
        ("85. Apa jenis kabel fiber optik untuk penggunaan luar ruangan?", "Outdoor-rated fiber dengan pelindung ekstra"),
        ("86. Bagaimana kabel fiber optik dibedakan?", "Berdasarkan mode, struktur, dan aplikasi"),
        ("87. Apa manfaat utama dari teknologi fiber optik dalam komunikasi global?", "Menyediakan koneksi cepat dan andal antar negara"),
        ("88. Apa itu GI dan SI dalam fiber multimode?", "Graded Index dan Step Index – tipe distribusi indeks bias"),
        ("89. Apa kelebihan GI dibanding SI?", "Mengurangi modal dispersion dengan distribusi indeks bertahap"),
        ("90. Mengapa fiber optik tidak menghantarkan petir?", "Karena tidak menghantarkan arus listrik"),
        ("91. Apa yang dilakukan patch panel dalam sistem fiber?", "Mendistribusikan dan mengatur sambungan serat optik"),
        ("92. Bagaimana cara menguji sambungan fiber?", "Menggunakan OTDR atau power meter"),
        ("93. Mengapa sinyal dalam fiber optik sulit terganggu?", "Karena transmisi menggunakan cahaya di dalam core tertutup"),
        ("94. Apa fungsi power meter dalam pengujian fiber optik?", "Mengukur kekuatan sinyal cahaya yang diterima di ujung fiber"),
        ("95. Apa itu core alignment dalam fusion splicing?", "Penyelarasan tepat antara dua core sebelum dilebur menjadi satu"),
        ("96. Apa itu loose tube cable?", "Jenis kabel fiber optik di mana serat optik tidak melekat langsung pada pelindung luarnya, cocok untuk luar ruangan"),
        ("97. Apa itu tight-buffered cable?", "Jenis kabel fiber optik di mana serat dilapisi langsung oleh bahan pelindung, cocok untuk dalam ruangan"),
        ("98. Apa itu armor dalam kabel fiber optik?", "Lapisan logam tambahan untuk perlindungan terhadap gigitan hewan atau tekanan fisik"),
        ("99. Mengapa penting menjaga kebersihan konektor fiber optik?", "Debu dapat mengganggu transmisi cahaya dan menyebabkan kehilangan sinyal"),
        ("100. Apa standar umum konektor untuk jaringan FTTH?", "Konektor tipe SC/APC untuk transmisi stabil dan minim pantulan")

    ],
    "3": [
        ("1. Apa dua jenis utama fiber optik berdasarkan mode transmisinya?", "Single-mode dan Multi-mode"),
        ("2. Berapa ukuran core pada single-mode fiber?", "8–10 µm"),
        ("3. Berapa ukuran core pada multi-mode fiber?", "50–62,5 µm"),
        ("4. Jenis fiber optik yang hanya mentransmisikan satu jalur cahaya adalah?", "Single-mode"),
        ("5. Jenis fiber optik yang dapat mentransmisikan banyak jalur cahaya adalah?", "Multi-mode"),
        ("6. Sumber cahaya pada single-mode fiber adalah?", "Laser"),
        ("7. Sumber cahaya pada multi-mode fiber adalah?", "LED"),
        ("8. Jenis fiber yang cocok digunakan untuk transmisi jarak jauh?", "Single-mode"),
        ("9. Jenis fiber yang cocok untuk jaringan lokal di gedung?", "Multi-mode"),
        ("10. Jenis fiber dengan biaya perangkat yang lebih murah adalah?", "Multi-mode"),
        ("11. Jenis fiber dengan redaman sinyal yang lebih rendah?", "Single-mode"),
        ("12. Jenis fiber yang biasa digunakan untuk backbone ISP?", "Single-mode"),
        ("13. Jenis fiber yang umum digunakan dalam jaringan LAN gedung?", "Multi-mode"),
        ("14. Keunggulan utama dari single-mode fiber adalah?", "Redaman rendah dan jarak jauh"),
        ("15. Keunggulan utama dari multi-mode fiber adalah?", "Instalasi mudah dan murah"),
        ("16. Apa fungsi utama dari OTDR?", "Mendeteksi redaman sinyal dan lokasi kerusakan fiber"),
        ("17. Apa fungsi dari konektor LC?", "Menyambungkan fiber optik pada perangkat SFP"),
        ("18. Apa alat untuk menyambung serat optik secara permanen?", "Fusion splicer"),
        ("19. Apa alat untuk memotong ujung fiber dengan presisi tinggi?", "Fiber cleaver"),
        ("20. Apa nama panel pengatur distribusi koneksi fiber?", "Patch panel fiber"),
        ("21. Apa perbedaan utama SMF dan MMF dari sisi sumber cahaya?", "SMF memakai laser, MMF memakai LED"),
        ("22. Apa kelebihan SMF dibanding MMF dalam hal jangkauan?", "Jangkauan SMF lebih jauh"),
        ("23. Jenis fiber yang ideal untuk transmisi kecepatan tinggi seperti 10 Gbps ke atas adalah?", "Single-mode"),
        ("24. Mengapa MMF tidak cocok untuk jarak jauh?", "Karena memiliki redaman dan distorsi lebih tinggi"),
        ("25. Apa aplikasi umum dari fiber optik dalam rumah?", "FTTH (Fiber To The Home)"),
        ("26. Apa arti FTTH?", "Fiber To The Home"),
        ("27. Untuk apa fiber optik digunakan dalam sistem keamanan?", "CCTV HD tanpa delay dan aman"),
        ("28. Apa contoh penggunaan fiber optik di dunia medis?", "Alat endoskop"),
        ("29. Mengapa fiber optik digunakan dalam militer?", "Karena aman dari penyadapan dan tahan kondisi ekstrem"),
        ("30. Jenis fiber yang digunakan di jaringan metropolitan adalah?", "Single-mode"),
        ("31. Apa manfaat menggunakan laser pada SMF?", "Transmisi cahaya lebih terfokus dan jangkauan lebih jauh"),
        ("32. Apa yang dimaksud mode dalam fiber optik?", "Jalur perambatan cahaya dalam core"),
        ("33. Fiber optik dengan ukuran core lebih kecil adalah?", "Single-mode"),
        ("34. Fiber optik dengan ukuran core lebih besar adalah?", "Multi-mode"),
        ("35. Mengapa biaya instalasi MMF lebih murah?", "Karena perangkat dan konektornya lebih terjangkau"),
        ("36. Dalam jaringan gedung bertingkat, jenis fiber apa yang sering digunakan?", "Multi-mode"),
        ("37. Untuk koneksi antar kota, jenis fiber yang digunakan adalah?", "Single-mode"),
        ("38. Jenis fiber yang cocok untuk kecepatan tinggi dan jarak jauh adalah?", "Single-mode"),
        ("39. Fiber optik memiliki keunggulan tahan terhadap apa?", "Gangguan elektromagnetik"),
        ("40. Apa yang membedakan SMF dan MMF dalam hal jumlah cahaya yang ditransmisikan?", "SMF satu jalur, MMF banyak jalur"),
        ("41. Apa keuntungan menggunakan konektor LC?", "Ukurannya kecil dan efisien di ruang terbatas"),
        ("42. Apa fungsi utama fusion splicer?", "Menyambung dua ujung serat optik"),
        ("43. Bagaimana prinsip kerja fiber cleaver?", "Memotong serat optik dengan presisi tinggi"),
        ("44. Kapan kita menggunakan patch panel fiber?", "Untuk manajemen koneksi fiber di rak jaringan"),
        ("45. Apa fungsi utama dari fiber optik dalam backbone?", "Menghubungkan jaringan antar gedung/kota"),
        ("46. Jenis fiber apa yang dipakai pada koneksi FTTH?", "Single-mode"),
        ("47. Apakah LED cocok untuk transmisi jarak jauh?", "Tidak"),
        ("48. Apakah laser cocok untuk transmisi jarak pendek?", "Kurang efisien dibanding LED"),
        ("49. Apa yang dimaksud dengan redaman pada fiber optik?", "Pelemahan sinyal selama transmisi"),
        ("50. Jaringan LAN gedung lebih cocok pakai fiber jenis apa?", "Multi-mode"),
        ("51. Apa kelebihan utama LED dibanding laser?", "Lebih murah dan cukup untuk jarak dekat"),
        ("52. Mengapa SMF lebih mahal?", "Karena perangkat optiknya lebih kompleks"),
        ("53. Apa keuntungan utama penggunaan fiber optik secara umum?", "Kecepatan tinggi dan tahan gangguan"),
        ("54. Apa jenis konektor umum pada perangkat SFP?", "LC"),
        ("55. Apa arti dari istilah 'backbone jaringan'?", "Penghubung utama antar segmen jaringan"),
        ("56. Berapa jarak maksimum MMF biasanya?", "Ratusan meter"),
        ("57. Berapa jarak maksimum SMF biasanya?", "Hingga ratusan kilometer"),
        ("58. Apakah semua fiber optik menggunakan sumber cahaya yang sama?", "Tidak"),
        ("59. Kapan kita memilih MMF daripada SMF?", "Jika jarak pendek dan biaya perlu ditekan"),
        ("60. Kapan kita harus memilih SMF?", "Jika butuh jangkauan jauh dan kecepatan tinggi"),
        ("61. Apa yang membuat SMF ideal untuk ISP?", "Jangkauan dan stabilitas tinggi"),
        ("62. Apakah MMF cocok untuk jaringan antar kota?", "Tidak"),
        ("63. Apakah MMF bisa digunakan untuk CCTV di satu gedung?", "Ya"),
        ("64. Salah satu alasan utama memilih SMF adalah?", "Minim distorsi dan kapasitas besar"),
        ("65. Apa dampak distorsi dalam fiber optik?", "Kualitas dan kecepatan transmisi menurun"),
        ("66. Jenis fiber dengan distorsi lebih tinggi adalah?", "Multi-mode"),
        ("67. Jenis fiber yang lebih mudah dipasang adalah?", "Multi-mode"),
        ("68. Jenis fiber yang lebih cocok untuk skala industri dan data center adalah?", "Single-mode"),
        ("69. Apa itu mode tunggal dalam fiber optik?", "Satu jalur cahaya dalam satu waktu"),
        ("70. Apa itu mode ganda atau multi-mode dalam fiber optik?", "Banyak jalur cahaya dalam satu waktu"),
        ("71. Ukuran core SMF membuat cahaya tetap pada satu jalur karena?", "Efek pembiasan terfokus"),
        ("72. Ukuran core besar pada MMF menyebabkan?", "Pencampuran banyak jalur cahaya"),
        ("73. Apakah fiber optik aman terhadap gangguan elektromagnetik?", "Ya"),
        ("74. Apa efek panjang gelombang terhadap transmisi di SMF?", "Semakin panjang, makin jauh jangkauan"),
        ("75. Apa fungsi utama OTDR saat instalasi fiber?", "Mengecek kualitas sambungan dan lokasi gangguan"),
        ("76. Apa alasan teknis menggunakan laser di SMF?", "Stabilitas dan daya fokus tinggi"),
        ("77. Mengapa MMF lebih cocok untuk lingkungan indoor?", "Karena jaraknya pendek dan biaya rendah"),
        ("78. Peralatan untuk instalasi fiber harus memiliki?", "Presisi tinggi dan kompatibilitas standar"),
        ("79. Apa yang terjadi jika koneksi fiber tidak tepat?", "Sinyal melemah atau terputus"),
        ("80. Fungsi utama fiber optik di militer adalah?", "Transmisi aman dan tahan lingkungan ekstrem"),
        ("81. Apa ciri khas dari patch panel fiber?", "Terorganisir dan mudah dalam pemeliharaan"),
        ("82. Kenapa kita butuh fiber cleaver?", "Agar sambungan fiber rapi dan optimal"),
        ("83. Alat yang digunakan untuk menyambung fiber secara mekanis atau fusi?", "Fusion splicer"),
        ("84. Alat yang bisa menunjukkan lokasi kerusakan di kabel fiber adalah?", "OTDR"),
        ("85. Apakah semua jaringan harus menggunakan fiber optik?", "Tidak, tergantung kebutuhan dan skala"),
        ("86. Apa arti istilah 'fiber backbone' dalam jaringan?", "Struktur utama penghubung jaringan"),
        ("87. Mengapa SMF lebih baik untuk ISP daripada MMF?", "Karena jangkauan jauh dan kecepatan lebih tinggi"),
        ("88. Jenis fiber optik mana yang memiliki biaya perangkat lebih murah?", "Multi-mode"),
        ("89. Jenis fiber optik mana yang lebih rumit instalasinya?", "Single-mode"),
        ("90. Sumber cahaya mana yang lebih tahan lama, LED atau laser?", "LED"),
        ("91. Fiber optik digunakan di rumah-rumah melalui skema apa?", "FTTH"),
        ("92. Apakah patch panel fiber hanya digunakan di ISP?", "Tidak, juga digunakan di gedung dan kantor"),
        ("93. Fiber optik cocok digunakan untuk jaringan dengan lalu lintas data tinggi karena?", "Bandwidth besar"),
        ("94. Penggunaan SMF lebih disarankan jika kita ingin?", "Kecepatan dan jangkauan maksimal"),
        ("95. Penggunaan MMF lebih disarankan jika kita ingin?", "Instalasi mudah dan biaya murah"),
        ("96. Apakah semua peralatan optik bisa digunakan untuk semua jenis fiber?", "Tidak, tergantung jenisnya"),
        ("97. Apa peran penting konektor LC dalam koneksi jaringan?", "Menyambungkan fiber dengan perangkat SFP"),
        ("98. Cahaya di dalam fiber optik merambat melalui apa?", "Core"),
        ("99. Bagian fiber optik yang dilapisi untuk memantulkan cahaya kembali ke core disebut?", "Cladding"),
        ("100. Apakah fiber optik bisa digunakan untuk audio dan video?", "Ya, dengan kualitas tinggi"),
    ]
}